version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: formafit-postgres
    environment:
      POSTGRES_DB: formafit
      POSTGRES_USER: formafit_user
      POSTGRES_PASSWORD: formafit_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data:
